name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
template: |
  $CHANGES

categories:
  - title: "Features"
    labels:
      - "feature"
  - title: "Fixes"
    labels:
      - "bug"
  - title: "Maintenance"
    labels:
      - "chore"
change-template: "- $TITLE (#$NUMBER)"
no-changes-template: "- No changes"
